{{- if .Values.provider }}
{{- if eq .Values.provider "aws" }}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: proxy-security-groups
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  securityGroups:
    groupIds:
{{ toYaml .Values.securityGroups | indent 4 }}
{{- end }}
{{- end }}